apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
spec: 
  replicas: {{ .Values.kafka.replicas }}
  oneReplicaPerNode: true
  image:
    application: confluentinc/cp-server:{{ .Values.version }}
    init: confluentinc/confluent-init-container:{{ .Values.initcontainer.version }}
  dataVolumeCapacity: 10Gi 
  configOverrides:
    server:
      - "confluent.license.topic.replication.factor={{ .Values.kafka.replicas }}"
      - "confluent.metrics.reporter.topic.replicas={{ .Values.kafka.replicas }}"
      - "confluent.tier.metadata.replication.factor={{ .Values.kafka.replicas }}"
      - "confluent.metadata.topic.replication.factor={{ .Values.kafka.replicas }}"
      - "confluent.balancer.topic.replication.factor={{ .Values.kafka.replicas }}"
      - "confluent.security.event.logger.exporter.kafka.topic.replicas={{ .Values.kafka.replicas }}"
      - "event.logger.exporter.kafka.topic.replicas={{ .Values.kafka.replicas }}"
      - "offsets.topic.replication.factor={{ .Values.kafka.replicas }}" 
      - "confluent.metadata.server.urls.fail.on.401=true"
      - "confluent.metadata.server.urls.max.retries=3" 
 tls:
    secretRef: kafka-tls
  listeners:
    external:
      tls:
        enabled: true
  metricReporter:
    enabled: true