apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.connect.replicas }}
  image:
    application: confluentinc/cp-server-connect:{{ .Values.version }}
    init: confluentinc/confluent-init-container:{{ .Values.initcontainer.version }} 
  build:
    type: onDemand
    onDemand:
      plugins:
        locationType: confluentHub
        confluentHub: 
        {{- range $.Values.connect.connectors }}
        - name: {{ .name }}
          owner: {{ .owner }}
          version: {{ .version }} 
        {{- end }}  
  tls:
    secretRef: connect-tls
