apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: {{ .Release.Namespace }}
spec:
  # license:
  #  globalLicense: true
  replicas: {{ .Values.connect.replicas }}
  image:
    application: confluentinc/cp-server-connect:{{ .Values.version }}
    init: confluentinc/confluent-init-container:{{ .Values.initcontainer.version }} 
  build:
    type: onDemand
    onDemand:
      plugins:
        locationType: confluentHub
        confluentHub: 
        {{- range $.Values.connect.connectors }}
        - name: {{ .name }}
          owner: {{ .owner }}
          version: {{ .version }} 
        {{- end }}  
  tls:
    secretRef: connect-tls
  authorization:
    type: rbac
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.{{ .Release.Namespace }}.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.{{ .Release.Namespace }}.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: connect-mds-client
      tls:
        enabled: true