apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: {{ .Release.Namespace }}
spec:
  # license:
  #  globalLicense: true
  replicas: {{ .Values.schemaregistry.replicas }}
  image:
    application: confluentinc/cp-schema-registry:{{ .Values.version }}
    init: confluentinc/confluent-init-container:{{ .Values.initcontainer.version }}
  configOverrides:
    server: 
    - "confluent.metadata.server.urls.fail.on.401=true"
    - "confluent.metadata.server.urls.max.retries=3"
  tls:
    secretRef: schemaregistry-tls
 