apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: {{ .Release.Namespace }}
spec: 
  replicas: {{ .Values.ksqldb.replicas }}
  image:
    application: confluentinc/cp-ksqldb-server:{{ .Values.version }}
    init: confluentinc/confluent-init-container:{{ .Values.initcontainer.version }}
  dataVolumeCapacity: 10Gi 
  tls:
    secretRef: ksqldb-tls
  