apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: {{ .Release.Namespace }}
spec:
  # license:
  #  globalLicense: true
  replicas: {{ .Values.ksqldb.replicas }}
  image:
    application: confluentinc/cp-ksqldb-server:{{ .Values.version }}
    init: confluentinc/confluent-init-container:{{ .Values.initcontainer.version }}
  dataVolumeCapacity: 10Gi
  authorization:
    type: rbac
  tls:
    secretRef: ksqldb-tls
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.{{ .Release.Namespace }}.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.{{ .Release.Namespace }}.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: ksqldb-mds-client
      tls:
        enabled: true
 