apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.controlcenter.replicas }}
  podTemplate:
    probe:
      liveness:
        periodSeconds: 10
        failureThreshold: 5
        timeoutSeconds: 500
  image:
    application: confluentinc/cp-enterprise-control-center:{{ .Values.version }}
    init: confluentinc/confluent-init-container:{{ .Values.initcontainer.version }}
  configOverrides:
    server:
      - confluent.controlcenter.id=0
      - confluent.controlcenter.ksql.ksqldb.advertised.url=https://ksqldb.{{ .Values.network.ingress }}.{{ .Values.network.domain }}
  dataVolumeCapacity: 10Gi
  tls:
    secretRef: controlcenter-tls
  dependencies: 
    connect:
      - name: connect
        url:  https://connect.{{ .Release.Namespace }}.svc.cluster.local:8083
        tls:
          enabled: true 
    ksqldb:
      - name: ksqldb
        url:  https://ksqldb.{{ .Release.Namespace }}.svc.cluster.local:8088
        tls:
          enabled: true 
    schemaRegistry:
      url: https://schemaregistry.{{ .Release.Namespace }}.svc.cluster.local:8081
      tls:
        enabled: true
      