apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: {{ .Release.Namespace }}
spec:
  # license:
  #  globalLicense: true
  replicas: {{ .Values.controlcenter.replicas }}
  podTemplate:
    probe:
      liveness:
        periodSeconds: 10
        failureThreshold: 5
        timeoutSeconds: 500
  image:
    application: confluentinc/cp-enterprise-control-center:{{ .Values.version }}
    init: confluentinc/confluent-init-container:{{ .Values.initcontainer.version }}
  configOverrides:
    server:
      - confluent.controlcenter.id=0
      - confluent.controlcenter.ksql.ksqldb.advertised.url=https://ksqldb.{{ .Values.network.ingress }}.{{ .Values.network.domain }}
  dataVolumeCapacity: 10Gi
  authorization:
    type: rbac
  tls:
    secretRef: controlcenter-tls
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.{{ .Release.Namespace }}.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.{{ .Release.Namespace }}.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: c3-mds-client
      tls:
        enabled: true
    connect:
      - name: connect
        url:  https://connect.{{ .Release.Namespace }}.svc.cluster.local:8083
        tls:
          enabled: true 
    ksqldb:
      - name: ksqldb
        url:  https://ksqldb.{{ .Release.Namespace }}.svc.cluster.local:8088
        tls:
          enabled: true 
    schemaRegistry:
      url: https://schemaregistry.{{ .Release.Namespace }}.svc.cluster.local:8081
      tls:
        enabled: true
      