apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  labels:
    service: vault
  annotations:
  namespace: vault
spec:
  releaseName: vault
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: vault
      chart: vault
      version: ~x.x.x 
  interval: 5m0s
  timeout: 5m0s
  values: 
    namespace: vault
    injector:
      replicas: 2  
      leaderElector: 
        enabled: false  
      certs: 
        secretName: injector-tls  
      webhookAnnotations: "cert-manager.io/inject-ca-from: vault/injector-certificate"