apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-cert
  namespace: confluent
spec:
  commonName: kafka.confluent.svc 
  subject:
    organizations:
      - local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - kafka
  - kafka.confluent
  - kafka.confluent.svc.cluster.local
  - '*.confluent.svc.cluster.local'
  - '*.kafka.confluent.svc.cluster.local' 
  - kafka-0.kafka.confluent.svc.cluster.local
  - zookeeper.confluent.svc.cluster.local  
  - zookeeper-0.zookeeper.confluent.svc.cluster.local
  - zookeeper-1.zookeeper.confluent.svc.cluster.local
  - zookeeper-2.zookeeper.confluent.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: kafka-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zookeeper-cert
  namespace: confluent
spec:
  commonName: zookeeper.confluent.svc
  subject:
    organizations:
      - local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames: 
    - zookeeper.confluent.svc.cluster.local  
    - zookeeper-0.zookeeper.confluent.svc.cluster.local
    - zookeeper-1.zookeeper.confluent.svc.cluster.local
    - zookeeper-2.zookeeper.confluent.svc.cluster.local
    - '*.zookeeper.confluent.svc.cluster.local'
    - '*.confluent.svc.cluster.local'
    - kafka-0.kafka.confluent.svc.cluster.local
    - kafka-1.kafka.confluent.svc.cluster.local
    - kafka-2.kafka.confluent.svc.cluster.local
    - kafka-3.kafka.confluent.svc.cluster.local
    - kafka-4.kafka.confluent.svc.cluster.local
    - '*.kafka.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: zookeeper-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: c3-cert
  namespace: confluent
spec:
  commonName: controlcenter
  dnsNames:
    - controlcenter
    - controlcenter.confluent
    - controlcenter.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.controlcenter.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: controlcenter-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ksqldb-cert
  namespace: confluent
spec:
  commonName: ksqldb
  dnsNames:
    - ksqldb
    - ksqldb.confluent
    - ksqldb.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.ksqldb.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: ksqldb-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sr-cert
  namespace: confluent
spec:
  commonName: schemaregistry
  dnsNames:
    - schemaregistry
    - schemaregistry.confluent
    - schemaregistry.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.schemaregistry.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: schemaregistry-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: connect-cert
  namespace: confluent
spec:
  commonName: connect
  dnsNames:
    - connect
    - connect.confluent
    - connect.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.connect.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: connect-tls