---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: injector-selfsigned-ca
  namespace: confluent
spec:
  isCA: true
  subject:
    organizations:
      - local
  commonName: Agent Inject CA
  secretName: injector-ca-secret
  duration: 87660h  # 10 years
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: injector-ca-issuer
  namespace: confluent
spec:
  ca:
    secretName: injector-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-cert
  namespace: confluent
spec:
  subject:
    organizations:
      - local
  commonName: Agent Inject CA
  isCA: false 
  usages:
    - server auth
    - client auth
  dnsNames:
    - kafka
    - kafka.confluent
    - kafka.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.kafka.confluent.svc.cluster.local'  
    - zookeeper.confluent.svc.cluster.local 
    - '*.zookeeper.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: injector-ca-issuer
  secretName: kafka-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zookeeper-cert
  namespace: confluent
spec:
  commonName: Agent Inject CA
  isCA: false 
  subject:
    organizations:
      - local
  usages:
    - server auth
    - client auth
  dnsNames: 
    - zookeeper.confluent.svc.cluster.local   
    - '*.zookeeper.confluent.svc.cluster.local'
    - kafka.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.kafka.confluent.svc.cluster.local'  
  issuerRef:
    kind: Issuer
    name: injector-ca-issuer 
  secretName: zookeeper-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: c3-cert
  namespace: confluent
spec:
  commonName: controlcenter
  dnsNames:
    - controlcenter
    - controlcenter.confluent
    - controlcenter.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.controlcenter.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: injector-ca-issuer
  secretName: controlcenter-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ksqldb-cert
  namespace: confluent
spec:
  commonName: ksqldb
  dnsNames:
    - ksqldb
    - ksqldb.confluent
    - ksqldb.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.ksqldb.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: injector-ca-issuer
  secretName: ksqldb-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sr-cert
  namespace: confluent
spec:
  commonName: schemaregistry
  dnsNames:
    - schemaregistry
    - schemaregistry.confluent
    - schemaregistry.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.schemaregistry.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: injector-ca-issuer
  secretName: schemaregistry-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: connect-cert
  namespace: confluent
spec:
  commonName: connect
  dnsNames:
    - connect
    - connect.confluent
    - connect.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.connect.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: injector-ca-issuer
  secretName: connect-tls