---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: injector-selfsigned-ca
  namespace: confluent
spec:
  isCA: true 
  commonName: injector-selfsigned-ca
  secretName: injector-ca-secret 
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: injector-ca-issuer
  namespace: confluent
spec:
  ca:
    secretName: injector-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-cert
  namespace: confluent
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: kafka.confluent.svc 
  isCA: false 
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
  dnsNames:
    - kafka
    - kafka.confluent
    - kafka.confluent.svc.cluster.local
    - "*.confluent.svc.cluster.local"
    - "*.kafka.confluent.svc.cluster.local"  
    - zookeeper.confluent.svc.cluster.local 
    - "*.zookeeper.confluent.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: injector-ca-issuer
  secretName: kafka-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zookeeper-cert
  namespace: confluent
spec:
  commonName: zookeeper.confluent.svc
  isCA: false  
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
  dnsNames: 
    - zookeeper.confluent.svc.cluster.local   
    - '*.zookeeper.confluent.svc.cluster.local'
    - kafka.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.kafka.confluent.svc.cluster.local'  
  issuerRef:
    kind: Issuer
    name: injector-ca-issuer 
  secretName: zookeeper-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: c3-cert
  namespace: confluent
spec:
  commonName: controlcenter
  dnsNames:
    - controlcenter
    - controlcenter.confluent
    - controlcenter.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.controlcenter.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: injector-ca-issuer
  secretName: controlcenter-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ksqldb-cert
  namespace: confluent
spec:
  commonName: ksqldb
  dnsNames:
    - ksqldb
    - ksqldb.confluent
    - ksqldb.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.ksqldb.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: injector-ca-issuer
  secretName: ksqldb-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sr-cert
  namespace: confluent
spec:
  commonName: schemaregistry
  dnsNames:
    - schemaregistry
    - schemaregistry.confluent
    - schemaregistry.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.schemaregistry.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: injector-ca-issuer
  secretName: schemaregistry-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: connect-cert
  namespace: confluent
spec:
  commonName: connect
  dnsNames:
    - connect
    - connect.confluent
    - connect.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.connect.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: injector-ca-issuer
  secretName: connect-tls