
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- issuer.yaml
- certificate.yaml
configurations:
- kustomizeconfig.yaml 
vars:
- name: NAMESPACE
  objref:
    kind: Certificate
    group: cert-manager.io
    apiVersion: v1
    name: kafka-cert
  fieldref:
    fieldpath: metadata.namespace