apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  labels:
    service: ingress-nginx
  annotations:
  namespace: kube-system
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      chart: ingress-nginx
      version: ~x.x.x

  interval: 5m0s
  timeout: 5m0s
  values: 
    controller.extraArgs.enable-ssl-passthrough: true