apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: openldap
spec:
  interval: 5m0s
  chart:
    spec:
      chart: ./charts/openldap
      sourceRef:
        kind: GitRepository
        name: gitrepo
        namespace: flux-system
      interval: 10m
      reconcileStrategy: Revision
 