apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  labels:
    service: prometheus-operator
  annotations:
  namespace: prometheus
spec:
  releaseName: prometheus-operator

  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: prometheus
      chart: kube-prometheus-stack
      version: ~x.x.x

  interval: 5m0s
  timeout: 5m0s
  values:
    commonLabels:
      monitoring-platform: prometheus 
    ## Hosts is a valid FQDN
    prometheus:
      ingress:
        enabled: true 
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          external-dns.alpha.kubernetes.io/hostname: prometheus.35.205.9.43.nip.io #FIX 
        hosts:
          - prometheus.35.205.9.43.nip.io #FIX
        tls:
          - secretName: prometheus-cert
            hosts:
              - prometheus.35.205.9.43.nip.io #FIX
        pathType: Prefix
      prometheusSpec:
        retention: 30d 
        serviceMonitorSelector:
          matchLabels:
            monitoring-platform: prometheus 
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi 
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
          limits:
            cpu: 4000m
            memory: 8192Mi

    grafana:
      enabled: true
      extraLabels:
        monitoring-platform: prometheus
      grafana.ini:
        auth.anonymous:
          enabled: true
          org_role: Viewer
        users:
          viewers_can_edit: true

      plugins:
        - grafana-piechart-panel

      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 256Mi

      sidecar:
        dashboards:
          searchNamespace: ALL

        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 256Mi
      ingress:
        enabled: true
        # ingressClassName: alb
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          external-dns.alpha.kubernetes.io/hostname: grafana.35.205.9.43.nip.io #FIX
          alb.ingress.kubernetes.io/target-type: ip
        hosts:
          - grafana.35.205.9.43.nip.io #FIX
        tls:
          - secretName: grafana-cert
            hosts:
              - grafana.35.205.9.43.nip.io #FIX

    nameOverride: "prometheus-operator"

    prometheusOperator:
      enabled: true
      createCustomResource: false
      manageCrds: false

      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 256Mi

    prometheus-node-exporter:
      resources:
        requests:
          cpu: 50m
          memory: 16Mi
        limits:
          cpu: 500m
          memory: 128Mi

    kube-state-metrics:
      customLabels:
        monitoring-platform: prometheus
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi